name: isabelle
favicon: null
layout_spectrum: 0.5963543651159853
typography_spectrum: 0.07321535516530275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9631346527021378
  lightness: 0.10315775568597019
  saturation: 0.1177924876101315
  rhythmicContrast: 0.2700885394588113
purpose: []
